services:
  redis-server:
    build: .
    container_name: redis_server
    volumes:
      - ./stats:/app/stats
    ports:
      - "6379:6379"
    privileged: true 
    pid: host
  redis-benchmark:
    image: redis
    cap_add:
      - CAP_SYS_PTRACE
      - CAP_SYS_ADMIN
    container_name: redis_benchmark
    entrypoint:
      - "sh"
      - "-c"
      - |
        until redis-cli -h redis_server ping; do
          sleep 1;
        done;
        redis-benchmark -h redis_server

